apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: colocation-memory-device-plugin
  namespace: kube-system
  labels:
    app: colocation-memory-device-plugin
spec:
  selector:
    matchLabels:
      app: colocation-memory-device-plugin
  template:
    metadata:
      labels:
        app: colocation-memory-device-plugin
    spec:
      containers:
        - name: colocation-memory-device-plugin
          image: docker.io/yuk1judaiii/i-device-plugin:latest # TODO
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins # 请求 kubelet.sock 发起调用，同时将 device-plugin gRPC 服务的 sock 文件写入该目录供 kubelet 调用
            - name: gophers # TODO
              mountPath: /etc/gophers
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: gophers # TODO
          hostPath:
            path: /etc/gophers
