apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: colocation-memory
spec:
  nodeName: cxl-server
  containers:
    - name: colocation-memory-container
      image: docker.io/library/busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          xxx.com/colocation-memory: "3"
        limits:
          xxx.com/colocation-memory: "3"